name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    # "timeout-minutes" <- Max number of minutes that your job can take (if job-execution-time > 360 mins, then github will cancel it). This can also be used in steps.
    timeout-minutes: 360
    steps:
      - name: echo a string
        run: echo "Hello from Nandu"
        # "continue-on-error" <- All other steps will run even if this first step fails
        continue-on-error: true
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
