name: Context

on:
  - push
  - pull_request

jobs:
  functions:
    runs-on: ubuntu-16.04
    steps:
      - name: dump
        run: |
          echo ${{ contains( 'hello', 'll')}}
          echo ${{ startsWith( 'hello', 'he')}}
          echo ${{ endsWith( 'hello', 'lo')}}
          echo ${{ format( 'Hello {0} {1} {2}', 'World', '!', '!')}}
  #! Output
  # true
  # true
  # true
  # Hello World ! !

  one:
    runs-on: ubuntu-16.04
    #! This job will only run on push request
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context (deliberate fail)
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: eccho "$GITHUB_CONTEXT"
      - name: Dump job context
        #! we can make this step run even if the previous step has failed (by using a job status function)
        # failure() <- This function only returns true if the previous step has failed.
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        # always() <- will run always even if the previous steps have failed
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
#! When a step fails any subsequent steps will not run

