name: Container

on:
  - push

jobs:
  node-docker:
    # So far I have ran my workflows on virtual machines, using some OS that GitHub Actions provides. But we can also use a docker container that will be installed on this virtual machine (ubuntu-latest) and then our step will run on it rather than directly on our virtual machine.
    runs-on: ubuntu-latest
    container:
      image: node:12.18.2-alpine3.10
      # Any step that we run, will run inside of this container and not directly in our host, which is our Virtual machine
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release

#! Output
#! Any steps we write inside of node-docker job, we run inside of the docker container.
# v12.18.2
# NAME="Alpine Linux"
# ID=alpine
# VERSION_ID=3.10.5
# PRETTY_NAME="Alpine Linux v3.10"
# HOME_URL="https://alpinelinux.org/"
# BUG_REPORT_URL="https://bugs.alpinelinux.org/"
