name: Encrypt & Decrypt File

on: pull_request

env:
  WF_ENV: Available to all jobs

jobs:
  decrypt:
    runs-on: ubuntu-latest
    steps:
      #! After below "uses" step, we have access to the files in our repository here, including our secret encrypted file which we need to decrypt here in our decrypt job.
      - uses: actions/checkout@v1
      - name: Decrypt file
        #! Enter the passphrase below to decrypt successfully (Add the passphrase as a secret in github)
        #? https://github.com/ChanManChan/github-actions-test/settings/secrets  <- Add the passphrase here
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Print our file content
        run: cat $HOME/secret.json
  create-random-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m "Random file"
          git push
