name: DockerContainers

on:
  - push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        # build: .
        # https://hub.docker.com/r/alialaa17/node-api
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        # we are running this step in our VM and not in our container
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "NandaGopalFromDocker", "address": "New Delhi"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
# In order for these two containers (app and mongo) to communicate between each other, we use service name as host name

# eg: in app.js
# mongoose.connect("mongodb://mongo:27017/users", {...}) instead of mongoose.connect("mongodb://localhost:27017/users") <- in docker in order to communicate with another container we use our service name.
