name: ContainersWithinSteps

on:
  - push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
        # A step that uses it's own container
      - name: Step with container
        # uses: actions/checkout
        # we can override the entry point of this docker image using the "with" key
        uses: docker://node:12.14.1-alpine3.10
        with:
          # this is also used to provide inputs to our actions
          entrypoint: "/bin/echo"
          args: "Hello World from step"
      - name: Log node version inside this docker image
        uses: docker://node:12.14.1-alpine3.10
        with:
          # path to the node exec file
          # type -a node <- path
          entrypoint: /usr/local/bin/node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "NandaGopalFromDocker", "address": "New Delhi"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
# ENTRYPOINT ['/bin/echo', 'Hello'] === echo "Hello"
# CMD ['World']
# When this container runs it will echo 'Hello World'
